# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jacked < Formula
  desc "Jacked is an open-source vulnerability scanning tool designed to help you identify and mitigate security risks in your Container Images and File Systems."
  homepage "https://www.carbonetes.com/"
  version "1.8.0"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/carbonetes/jacked/releases/download/1.8.0/jacked_1.8.0_darwin_arm64.tar.gz"
      sha256 "0dc1c41c8503b15db4bbdbf8263cd8ac7c12622df0a840ba9f2c43e498dddbce"

      def install
        bin.install "jacked"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/carbonetes/jacked/releases/download/1.8.0/jacked_1.8.0_darwin_amd64.tar.gz"
      sha256 "70e54829820c4779139429ccdff29153cb17906c2bf803d5b9094afa36700b2e"

      def install
        bin.install "jacked"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/carbonetes/jacked/releases/download/1.8.0/jacked_1.8.0_linux_arm64.tar.gz"
      sha256 "cf980178ef738c4b54e1bf02ddb5c506cc93472dddc12803177d3fad89d22a3f"

      def install
        bin.install "jacked"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/carbonetes/jacked/releases/download/1.8.0/jacked_1.8.0_linux_amd64.tar.gz"
      sha256 "ba70c750400e32cc10ec5852e69c6bdeba02aa2a8eb4ac333206777cdeba57ec"

      def install
        bin.install "jacked"
      end
    end
  end
end
