# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jacked < Formula
  desc "Jacked is an open-source vulnerability scanning tool designed to help you identify and mitigate security risks in your Container Images and File Systems."
  homepage "https://www.carbonetes.com/"
  version "1.12.1"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/carbonetes/jacked/releases/download/v1.12.1/jacked_1.12.1_darwin_amd64.tar.gz"
      sha256 "991fc8ee9cad7e5c32a446c2470ef437f746b3082282661b4550744bc44b1aa6"

      def install
        bin.install "jacked"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/carbonetes/jacked/releases/download/v1.12.1/jacked_1.12.1_darwin_arm64.tar.gz"
      sha256 "b8d24f8a8b98c756f820d321c6ca5b1bd9093b9d551b357b0ccf47f724cb837a"

      def install
        bin.install "jacked"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/carbonetes/jacked/releases/download/v1.12.1/jacked_1.12.1_linux_amd64.tar.gz"
      sha256 "670ee5f3796f162c92bbbcd9005e2b78591aa9bacff044009c699434401f7e05"
      def install
        bin.install "jacked"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/carbonetes/jacked/releases/download/v1.12.1/jacked_1.12.1_linux_arm64.tar.gz"
      sha256 "1d91a7cada82bf2e0b7693c75f9ad602e30f1071e3e626a2c03cc98ab0de2417"
      def install
        bin.install "jacked"
      end
    end
  end
end
